package demo.calculate_insurance_amount;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CalculatedElement implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String key;
   private java.lang.Double doubleValue;

   public CalculatedElement()
   {
   }

   public java.lang.String getKey()
   {
      return this.key;
   }

   public void setKey(java.lang.String key)
   {
      this.key = key;
   }

   public java.lang.Double getDoubleValue()
   {
      return this.doubleValue;
   }

   public void setDoubleValue(java.lang.Double doubleValue)
   {
      this.doubleValue = doubleValue;
   }

   public CalculatedElement(java.lang.String key, java.lang.Double doubleValue)
   {
      this.key = key;
      this.doubleValue = doubleValue;
   }

}