package demo.calculate_insurance_amount;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CalculatedAgeElement implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String key;
   private java.lang.Double doubleValue;

   private org.chtijbug.drools.carinsurance.model.Driver driver;

   public CalculatedAgeElement()
   {
   }

   public java.lang.String getKey()
   {
      return this.key;
   }

   public void setKey(java.lang.String key)
   {
      this.key = key;
   }

   public java.lang.Double getDoubleValue()
   {
      return this.doubleValue;
   }

   public void setDoubleValue(java.lang.Double doubleValue)
   {
      this.doubleValue = doubleValue;
   }

   public org.chtijbug.drools.carinsurance.model.Driver getDriver()
   {
      return this.driver;
   }

   public void setDriver(org.chtijbug.drools.carinsurance.model.Driver driver)
   {
      this.driver = driver;
   }

   public CalculatedAgeElement(java.lang.String key, java.lang.Double doubleValue,
         org.chtijbug.drools.carinsurance.model.Driver driver)
   {
      this.key = key;
      this.doubleValue = doubleValue;
      this.driver = driver;
   }

}