package demo.calculate_insurance_amount;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CalculatedElement implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CalculatedElement() {
    }

}