package demo.calculate_insurance_amount;


import java.util.Calendar;
import java.util.Date;
import java.math.BigDecimal
import java.util.Collection;
import java.lang.Double;





function double AgeCalculationYear(Date d1,Date d2) {
	Calendar c1 = Calendar.getInstance();
	c1.setTime(d1);
	int day1=   c1.get(Calendar.DAY_OF_MONTH);
	int month1 = c1.get(Calendar.MONTH);
	int year1 = c1.get(Calendar.YEAR);
	Calendar c2 = Calendar.getInstance();
	c2.setTime(d2);
	int day2=   c2.get(Calendar.DAY_OF_MONTH);
	int month2 = c2.get(Calendar.MONTH);
	int year2 = c2.get(Calendar.YEAR); 
	double val1= (year2-year1);
	double val2=(month2-month1)/12.0;
	double val3=(day2-day1)/365.0;
	double age = val1+val2+val3;
	return age;
}
function double AgeCalculationMonth(Date d1,Date d2) {
	Calendar c1 = Calendar.getInstance();
	c1.setTime(d1);
	int day1=   c1.get(Calendar.DAY_OF_MONTH);
	int month1 = c1.get(Calendar.MONTH);
	int year1 = c1.get(Calendar.YEAR);
	Calendar c2 = Calendar.getInstance();
	c2.setTime(d2);
	int day2=   c2.get(Calendar.DAY_OF_MONTH);
	int month2 = c2.get(Calendar.MONTH);
	int year2 = c2.get(Calendar.YEAR); 
	double val1= (year2-year1)*12;
	double val2=(month2-month1);
	double val3=(day2-day1)/30.0;
	double age = val1+val2+val3;
	return age;
}


